### PR TITLE
HW0-ish: spelling changes

### PR DESCRIPTION
**Pull request by PaulDeStefano**
Just thought I would do the unofficial assignment you mentioned in class the first day, before starting on the real homework.  More soon.

### CODE REVIEW

**Comment by mjuric** [comment]
Hi Paul,
   Nice work, with one problem -- the .html file you edited is actually generated from lecture.ipynb; that's where those changes need to be made. Could you do them there and resubmit the pull request?

**Comment by PaulDeStefano** [comment]
Ah, I see.  Okay, I'll modify the notebook, instead.

Hmm, I'm new to pull requests; don't know the proper work-flow.  So, it looks like my new commits were automatically added to the pull request I started two days ago.  I think that means I don't need to close this pull request and start a new one.  Let me know if that's best practice or not.

Also, I didn't revert the two commits you didn't accept since I don't think it matters and that would just make two more commits you would need to skip over.

BTW, how do you generate the HTML file from the notebook?

**Comment by mjuric** [comment]
Hi Paul,
   Good pull request!

I cleaned it up a bit, and I didn't merge the changes that changed 'dataset' to 'data set'. The former is de-facto accepted as the proper spelling when referring to the technical term (i.e., a data set in digital form).

FYI, here's (roughly) what I did:
* From my master, created another branch to host/test your changes: `git checkout -b PaulDeStefano-master master`
* Pulled your changes in: `git fetch git://github.com/PaulDeStefano/ast597b.git master` followed by `git reset --hard FETCH_HEAD`
* Reviewed your changes using `git log`, `git diff`, and `git show`
* Removed your first two commits (the ones that edited the .html file), and the last one (the one that changed dataset to data set) by using `git rebase -i master`.
* Merged your changes into my master, and pushed it back to github: `git checkout master; git merge --no-ff PaulDeStefano-master; git push`. In the commit message (that was added in the `git merge` step), I also added the magic words "closes #2", which github parsed and automatically closed this PR (that is why above here it says:

image

**Comment by mjuric** [comment]
Regarding how one generates .html from .ipynb, it's using nbconvert (e.g., `ipython nbconvert talk.ipynb --to slides --post serve`). See http://ipython.org/ipython-doc/1/interactive/nbconvert.html for more info.

**Pull request closed without merging**
